import Footer from './components/Footer'
import Navbar from './components/Navbar'
import './globals.css'
import { Open_Sans } from 'next/font/google'

const open_Sans = Open_Sans({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`bg-primary-color-300 text-white ${open_Sans.className}`}
            >
                <Navbar />
                {children}
                <Footer />
            </body>
        </html>
    )
}
